### ISSUE TITLE
[Feature Request] Fan Controll Depending on the Power Mode

### ISSUE THREAD

**Issue by alantoblooddy** [BartoszCichecki/LenovoLegionToolkit#103]
Hi,

It would be neat to make a collaboration with LegionFanControl or develop some alternative that would incorporate into the app (LegionToolkit) itself.

**About App:**
LegionFanControl allows users to set fans according to the "Power Mode" chosen. The fan speed can be adjusted depending on the temperature you choose, and you can change only five levels.

![Снимок экрана 2022-05-24 132535](https://user-images.githubusercontent.com/22687186/170011211-0d282b4d-4ae1-498c-8742-a91765c488ed.png)

**Context:**
Recently I've upgraded from Legion5 2020 to Legion7Gen6, and the fans keep spinning although I do nothing serious (browsing, watching videos, chatting). The same issue I've got with the L5, but after uninstalling the Vantage software, the laptop didn't spin the fans if I wasn't gaming. Sadly, that's not the case with L7. Even after I uninstalled Vantage, the fans don't even consider stopping. However, I do realize that the thermal compound needs some time to evenly spread across the die after a good amount of gaming/stress tests.

**Disclaimer:**
This is not a promotion of other apps.

**Comment by BartoszCichecki** [comment]
Hey, I have been in touch with the author for LFC previously about other stuff, so I don't see a problem. I think you should contact him first. The reason is that technically the monitoring of power modes can be done directly in LFC without the need of LLT at all. We could do an integration between the two, but it does not seem necessary. LLT is also open source so the author of LFC is more then welcome to take a peek at the power mode monitoring code and use it in LFC.
