### ISSUE TITLE
When directly connected to the graphics card，CPU core frequency and utilization are not displayed

### ISSUE THREAD

**Issue by Li-owo** [BartoszCichecki/LenovoLegionToolkit#1040]
### Rules

- [ ] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [ ] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

win11 22h2

### Device

Legion Y9000P IAH7H

### BIOS version

J2CN49WW

### What's wrong?

![1700619713221](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/120236265/babdfa80-0ced-41d7-959f-d02f112afe84)

### How to reproduce the bug?

Enable independent graphics card direct connection

### What is the behavior that you expected?

display CPU core frequency and utilization

### Logs

。。。

**Comment by BartoszCichecki** [comment]
Logs please.

**Comment by Li-owo** [comment]
And Fn+R is invalid，Unable to switch refresh rate

**Comment by BartoszCichecki** [comment]
CPU usage and frequency isn't shown because LLT can't access Windows performance counters:

```

[23/11/2023 01:40:52.081] [24] [SafePerformanceCounter.cs#49:TryCreateIfNeeded] Failed to create performance counter. [categoryName=Processor Information, counterName=% Processor Utility, instanceName=_Total]
=== Exception ===
System.InvalidOperationException: Category does not exist.
```

I don't know if you are using some sort of modified Windows or something is broken in your install but this isn't an issue on my side.

Regarding Fn+R: I don't see any events in the log related to this which means that most likely it isn't supported on your laptop.
