### ISSUE TITLE
[FEAT] Disable TouchPad automatically when mouse is plugged in with a Toggle Switch On Off

### ISSUE THREAD

**Issue by mbze430** [BartoszCichecki/LenovoLegionToolkit#1072]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.17.0

### OS

Windows 11 23H2

### Device

Legion 9i

### Is your feature request related to a problem?

No

### How would you like the problem to be solved?

If possible, make a feature that can be toggled On and Off for users if they want it or not.

When a ext mouse device is detect turn off trhe built in touchpad.

### What alternatives have you considered?

I checked all the Actions but I didn't see anything that would help do this.

**Comment by BartoszCichecki** [comment]
There already is an option for this in Windows:

![Screenshot 2023-12-09 193019](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/7916915/5773e43e-7a97-42cd-9258-5067b9df1e3d)

It doesn't work well since many apps install virtual mice for macros etc. and Windows sees a mouse connected even none are actually plugged in. Unfortunately that won't work well in LLT either, since there is no possibility to tell virtual and real mice apart.

Because of this I am closing this ticket.
