### ISSUE TITLE
Add Time range trigger for Multiple Trigger option.

### ISSUE THREAD

**Issue by odie1185** [BartoszCichecki/LenovoLegionToolkit#1219]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.20.2

### OS

Win 11 Pro 22H2

### Device

Legion S7i 16IRH8

### Is your feature request related to a problem?

No

### How would you like the problem to be solved?

Current LLT Supports a trigger for a specific time, The ability to have a range would be awesome. 
Example: between 11 pm and 7 am && When a user becomes active; Do stuff

### What alternatives have you considered?

Another approach would be the ability to run an action with the Windows task scheduler

**Comment by BartoszCichecki** [comment]
This idea isn't bad, the main issue is that currently Actions (or rather the `AutomationProcessor`) is designed to be even driven and stateless. This means that while a specific time (like 9:00am) is a single event that can trigger a run of Actions, a time range isn't. `AutomationProcessor` would need to "remember" if it already ran in a given time range, which introduces complexity, like "clearing" it's memory next day, so that it can run again.

I don't see enough value at the moment to make the architecture more complex, just for this, so I am putting this issue on hold.

**Comment by odie1185** [comment]
I understand, thank you for reading and responding. Would running an action with command line be considered? I might be able to achieve the same results with task scheduler.

**Comment by BartoszCichecki** [comment]
Command line parameters for LLT were or _are_ something that was/is on the table, but there wasn't much push for it. I will see how much time I have, and consider making one for Actions only - maybe it's a good thing to start with.

**Comment by Ace-Radom** [comment]
@BartoszCichecki I would like to give a try on this cl parameters when I finish things on my hand. Would you rather use IPC to send triggered quick actions to LLT which is already running (as a host) than just read the action list and do the job before ensuring single instance?

**Comment by odie1185** [comment]
I think that would work well. For right now, I've achieved this by making a few PowerShell scripts that run on login and logoff and do different things depending on the current time.

**Comment by BartoszCichecki** [comment]
Resolved in #1338
