### ISSUE TITLE
Power Modes

### ISSUE THREAD

**Issue by A6ell** [BartoszCichecki/LenovoLegionToolkit#1238]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.20.2

### OS

Windows 23H2 Build 22631.3374

### Device

Legion Pro 5 16IRX8

### Is your feature request related to a problem?

Ways to change the power modes on my Legion device already exist, which is great, but the current method in actions is not very convenient for me. I appreciate having this feature but would like to find a more user-friendly setup.

### How would you like the problem to be solved?

I would really appreciate it if a feature similar to the Windows 10 toolbar, where clicking it brings up power options, could be added. I found this feature very convenient and was disappointed when Microsoft removed it. Implementing this feature, possibly through the Legion Toolkit, would provide a great user experience. I'm confident that the UI design would look excellent, given the quality of work you've demonstrated in the Legion Toolkit.

### What alternatives have you considered?

I'm currently using Actions to create quick profiles for each mode on my Legion device.
![Screenshot 2024-04-06 022809](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/131554641/ab921fbb-7d28-4e96-9cc2-06c65f78becc)
Additionally, I'm also using G-Helper, which is designed for ASUS devices but still allows me to modify default power modes on Windows. This setup is unconventional, but it's more efficient than having to launch settings every time I need to adjust power modes.
![Screenshot 2024-04-06 023022](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/131554641/11d137e4-3115-484f-9486-118ed7252e4f)

**Comment by BartoszCichecki** [comment]
Ok, but don't you have that now under right click?

**Comment by A6ell** [comment]
I do have access to the power options through right-click, but it doesn't include all the standard Windows power modes and I think it would look better if these options were presented in a toolbar format similar to the image plus If it's not too much to ask, you could develop standalone software that offers this functionality for all Windows laptops I believe many people would appreciate having an easy way to switch between default power modes.

**Comment by BartoszCichecki** [comment]
> doesn't include all the standard Windows power modes

You are confusing things. Power Modes in LLT **are not** the same as Windows power plans. They are completely separate things. In general, Lenovo delivered 3 Windows power plans that were assigned to each power mode, so when you switch power mode, matching power plan will also be activated. This is what you can configure in LLT settings.

If, you want to use more power plans, which almost never makes sense, you are free to do so and if you want to have access to power plans from tray, use something like https://github.com/petrroll/PowerSwitcher. In general, Microsoft is phasing out power plans, because they don't make much sense these days, you can pretty much just stick with only 1 power plan: the default "Balanced" power plan.

>  you could develop standalone software that offers this functionality for all Windows laptops

There is zero incentive to do so.

**Comment by A6ell** [comment]
Thank you for clarifying. Regarding GHelper, I'm not entirely sure, but it does seem like it's changing the profile

https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/131554641/a9264d22-7366-4fb2-b942-3512b24dcfd2

**Comment by BartoszCichecki** [comment]
It's not a profile or anything like that. It's a power plan overlay (which for some reason is called Power Mode) is  and for that there is already an issue reported: #1078

The likeliness of this being done is low, since there isn't much point in modifying it. Just set it to Best performance when on AC, and to Better battery while on battery and Windows will remember it.

**Comment by A6ell** [comment]
Thanks for explaining. I didn't know that. I appreciate your time and help!
