### ISSUE TITLE
dGPU disconnects and connects repeatedly on Hybrid Auto on AC -  Legion 7 16IRX9

### ISSUE THREAD

**Issue by sohrabhamza** [BartoszCichecki/LenovoLegionToolkit#1266]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.21.2

### OS

Windows 11 23H2 22631.3527

### Device

Legion 7 16IRX9

### BIOS version

NSCN23WW

### What's wrong?

When on hybrid auto mode: 
1) GPU shows inactive: Performance mode unknown
2) Core clock and Memory Clock Spike to 100% (Utilization 0)
3) Goes back down 
4) GPU shows powered off
5) GPU Disconnects
6) GPU reconnects 
... Repeat

Only the case on AC Power 
On battery works as expected

No apps using the dGPU. 

Peculiarly, each time this happens, the GPU number in the task manager goes up by 1

### How to reproduce the bug?

1. Be on AC 
2. Enable Hybrid Auto Mode
3. Observe 

### What is the behavior that you expected?

While on AC
The dGPU should stay connected and usage should not randomly spike 

### Logs

[log_2024_05_01_13_13_53.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/15177395/log_2024_05_01_13_13_53.txt)

### Additional information

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/66321101/5df7fbaf-770f-4785-a308-bca6052bfa26)

**Comment by BartoszCichecki** [comment]
Same as #1267:

LLT only tells EC what is the desired setting, but the process of connecting disconnecting is handled by firmware. I suggest resetting EC - instruction can be found in the Discord server: https://discord.com/invite/legionseries

**Comment by sohrabhamza** [comment]
This seems to only be a bug with LLT. 
Unable to reproduce with vantage. Works as described and GPU does not disconnect while plugged in at all.

**Comment by BartoszCichecki** [comment]
The problem is that LLT doesn't control when the dGPU is reconnected - it is entirely up to EC. I can see in the logs that LLT is receiving repeatedly messages from Windows that a new display device (aka GPU) was connected to the system:

```
[01-05-2024 13.14.12.828] [1] [NativeWindowsMessageListener.cs#111:WndProc] Event received: Display Device Arrival
```

but no action regarding Hybrid Mode is taken by LLT, when this happens. Whatever the issue is, it is not with LLT. Hybrid modes are unchanged since at least a couple months ago, and with no other issues reported so far, this basically means that this is an issue isolated to your laptop.

What is causing this, I don't know, but what you described here and in #1267 is not normal and until there are more reports like this from Gen 9 laptops, there is no reason for me to look into this.

If anything changes this issue will be re-opened.
