### ISSUE TITLE
Legion 5p 15arh05h

### ISSUE THREAD

**Issue by XipXiao** [BartoszCichecki/LenovoLegionToolkit#13]
Hello i would like to inform you that this program is not compatible with lenovo legion 5p 15arh05h running windows 10 x64. I installed net framework 5 1st but after , when opening the install package i get a message saying my laptop is not compatible.

**Comment by Elrondolio** [comment]
As provided in the instructions on this project page, you need to create a shortcut to the exe then edit that shortcut to add --skip-compat-check to the end as an argument.  This lets it run on your system.  If all features work correctly, you report back here with your model and it gets added to the compatibility list in future builds.  It is near certainly compatible with your laptop.

**Comment by XipXiao** [comment]
ok i see ty , will do and get back to you .

**Comment by XipXiao** [comment]
Hello again. So i managed to install this app as you said by adding that line to the shortcut. It works absolutely great. Ive tested all my settings to be exactly like they were and it all great. There is 1 thing i would like you to investigate further if possible. Is it possible that lenovo vantage software can influence the temps of the cpu ? After installing your app nd rebooting several times , i kept doing several cinebench and geekbench benchmarks for my peace of mind hehe. My cpu temps dropped with 5C in average while doing these tests. This is not a placebo effect . I havent installed anything in the past week, and i always do tests daily . Rom temps havent changed posision of laptop or cooling pad hasnt changed , i dont even use laptop keyboard or screen cause of external keyboard and display. So everything is exactly how it was before . Scores havent increased by much tho by a bit for sure yet temps never reached 95 C like on previous 123124123 tests ive been doing.

**Comment by Elrondolio** [comment]
I am not the main dev or a contributor on this utility, just someone who saw your comment and was giving you the info needed to get it to run on your system as provided by the main dev.  Glad it worked for you, however.  As to your lower temps: it is certainly possible that disabling Vantage could lower your temps somewhat as it's background services does use 5-7% CPU cycles just sitting idle (in my experience, at least).  While a 5 degree drop seems a tad high for this, its not out of the realm of possibility.  That is one of the main reasons for this tool to be developed, to disable Vantage (without needing it to be uninstalled and reinstalled all the time) since it is indeed a bit of a CPU hog for little reason.  All the best to you and yours.

**Comment by BartoszCichecki** [comment]
Thanks for support! Compatibility will be added in 1.2.
