### ISSUE TITLE
Low keyboard backlight brightness is not low

### ISSUE THREAD

**Issue by awesomenow42** [BartoszCichecki/LenovoLegionToolkit#1318]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.22.1

### OS

Windows 11 23H2 (22631.3672)

### Device

Legion 5 16IRX9

### BIOS version

NMCN22WW

### What's wrong?

The low brightness level is just below the high and far from the low Vantage. Burns out eyes :/

### How to reproduce the bug?

LLT - Keyboard - Preset - Brightness - Low

### What is the behavior that you expected?

Low brightness level

### Logs

[log_2024_06_02_17_20_12.txt](https://github.com/user-attachments/files/15526272/log_2024_06_02_17_20_12.txt)

### Additional information

The difference is small, it’s not even visible in the photo

  ![photo_2024-06-02_20-28-50](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/171505401/88aae43b-43f3-48e4-b52e-f9982b95ad8c)

**Comment by BartoszCichecki** [comment]
How many brightness levels do you have in Vantage?
Is the High brightness set in Vantage same as high in LLT?

**Comment by awesomenow42** [comment]
> How many brightness levels do you have in Vantage? Is the High brightness set in Vantage same as high in LLT?

Vantage also has 2 brightness levels: High and Low. Low is noticeably lower than high. In Toolkit, Low is almost the same as High. I hope not higher, since my keys are hot :D. High end between Vantage and Toolkit feels identical. Toolkit is very convenient and pleasant, except for this incident with brightness. Thank you.

**Comment by BartoszCichecki** [comment]
I was told by another L5P gen8 user that Vantage on his machine has similar behavior: very small difference between low and high levels.

I am wondering what is going on here, because:

https://github.com/BartoszCichecki/LenovoLegionToolkit/blob/f9e8af4a301bd02958818b04ab433b5639194170/LenovoLegionToolkit.Lib/Controllers/RGBKeyboardBacklightController.cs#L336-L341

As you can see High brightness has value `2`, Low has value `1` and `0` is off. That makes me a bit puzzled because as you can see there isn't really anything in between I can send to the RGB controller - these all are integer numbers, so fractions are a no go.

**Comment by awesomenow42** [comment]
It's sad, because in Vantage the difference looks like this:

![photo_2024-06-03_23-14-40](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/171505401/3d00f8b5-8b76-485f-9764-0f94452ed1f4)
![photo_2024-06-03_23-14-44](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/171505401/72989b83-7367-4c7a-8c93-15eca0b14b23)

But other than that, I don't like Vantage and would like to delete it.

**Comment by BartoszCichecki** [comment]
Until I get more clarity on this, I can't do much. I suggest using a darker color. For example, instead of settings white R:255 G:255 B:255 set it to dark grey R:128 G:128 B:128 - this way the color will be darker. In fact I am suspecting is that is what Vantage does, because the RGB controller doesn't have many options on 4-zone keyboards.

**Comment by awesomenow42** [comment]
Unfortunately, I don’t know how else I can contribute in this issue. However, in Toolkit 2.22.1 and Vantage 10.2403.25.0 I use the exact color R 22 G 75 B 153.
Your proposal is interesting, maybe there really is truth in this.

**Comment by electricalastro** [comment]
Hey, i recently started using LLT and found myself switching back and forth between Vantage and it because the backlight brightness is too bright even on Low

> Until I get more clarity on this, I can't do much. I suggest using a darker color. For example, instead of settings white R:255 G:255 B:255 set it to dark grey R:128 G:128 B:128 - this way the color will be darker. In fact I am suspecting is that is what Vantage does, because the RGB controller doesn't have many options on 4-zone keyboards.

This is indeed what appears to be happening with Vantage, i did a little POC to add an extra brightness option to match Vantage's Level 1 setting and it seems to be matching pretty closely

![LOW (Brightness Level 1 with dimming)](https://github.com/user-attachments/assets/aa318d8e-914e-424b-b2f7-4f662fed2cae)
![MED (Brightness Level 1)](https://github.com/user-attachments/assets/8390b94e-a29a-4d67-89eb-a71bbf572bca)
![HIGH (Brightness Level 2)](https://github.com/user-attachments/assets/7a31911f-f65f-4ac7-88e1-437f017d7313)
