### ISSUE TITLE
Battery conservation (80%) doesn't work with Legion C135 charger or generic 65W

### ISSUE THREAD

**Issue by cstrife1** [BartoszCichecki/LenovoLegionToolkit#1379]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

 2.22.2

### OS

Windows 11 64bit 23H2

### Device

Legion 7i Pro 13900HX RTX4080

### BIOS version

KWCN42WW

### What's wrong?

Battery will charge to 100% even with conservation mode enabled. 

This works properly with the included 330W power adapter.

Does not work with the C135 (135W) charger or generic (Onko) 3 port 65W charger.

It DOES work properly with the C135 charger when using Lenovo Vantage (newest version as of 2024-08-01).

### How to reproduce the bug?

Turn on conservation mode.

### What is the behavior that you expected?

Charge to 80% then stop with any charger.

### Logs

No logs after uninstalling and going to Vantage.

Let me know if this is important. I'll have to uninstall and reinstall LTT again.

**Comment by BartoszCichecki** [comment]
I have a confirmation from another user that this problem the behaviour is correct with Lenovo's USB-C charger connected both via USB-C and Slim Tip adapter and charging stops at 80%.

![image](https://github.com/user-attachments/assets/4f1e5c11-c0af-41b1-849b-eca44ebab8ac)

I suggest doing an EC reset (instructions can be found in the Legion Series Discord), if this issue is still there for your, because both LLT and Vantage use the same function of the Energy Driver to control this.
