### ISSUE TITLE
Change LLT color depending on GPU state

### ISSUE THREAD

**Issue by brupec** [BartoszCichecki/LenovoLegionToolkit#1417]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.24.0

### OS

Windows 11 22H2 latest updates

### Device

Legion Slim 5 16IRH8

### Is your feature request related to a problem?

No

### How would you like the problem to be solved?

Changing LLT tray color depending of gpu state
iGpu: red (actual)
dGpu: green
also, could be interesting to have info on what process is using dGpu if it is used, when passing mouse over icon, but that I imagine is more complicated, just mentioning idea

### What alternatives have you considered?

Using nvidia tray icon, what i'm doing now, but that would avoir one icon, and every once in a while nvidia icon disapear and needs to be activated/deactivated manually

**Comment by BartoszCichecki** [comment]
Hey, while this is a nice idea, it will not be added.

LLT aims to have lowest possible resource usage, which means that when it's minimized, most monitoring is stopped to reduce CPU and memory usage, ergo, dGPU monitoring isn't running as well. So called "tray monitoring" could be a possibility, to show additional information, but adding more icons - changing the main icon isn't really a good option. Giving all that, as you said it is a better idea to use the dGPU status provided by NVIDIA (since it already monitors dGPU usage in background).

**Comment by brupec** [comment]
Okay, I understand! Thanks for taking time to analyze it, and answer, and thanks again for that great soft :-)
