### ISSUE TITLE
My computer crashes in about 2 minutes....

### ISSUE THREAD

**Issue by ecsjjgg** [BartoszCichecki/LenovoLegionToolkit#1432]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.24.1

### OS

Windows 11 24H2

### Device

Legion  5-17ACH6H Type 82JY

### BIOS version

GKCN65WW

### What's wrong?

When I install Legion Toolkit, my computer just crashes and reboots, then it crashes within 2 minutes constantly, I had to restore it to an earlier state for the crashes to end...

I don't know if I've made any settings in the toolkit that causes these crashes...

### How to reproduce the bug?

Just install Legion Toolkit on a 5-17ACH6H, running win 11 24H2

### What is the behavior that you expected?

My computer should run smoothly, just as it does without the toolkit installed

### Logs

I haven't got any logs

### Additional information

No valid crashdumps where created...

**Comment by BartoszCichecki** [comment]
I can't do anything with this until you provide logs or crash dumps that show LLT causing this.

Long time ago there was a bug with GKCN BIOSes on Legion 5 and 5 Pro that would instantly crash the system. You can check Arguments section in readme and force disable Lenovo lighting to see if that fixes the issue - which is unlikely because on GKCN bioses LLT ignores lighting controls.


Also, from what you wrote is unclear whether if the crash occurs when LLT is running or not. Or in general what do you do just before the crash.

If you provide more info that points towards LLT we can reopen this issue.

**Comment by acelbyte** [comment]
In early 2024 i have nothing error or system crashes. But in early July, the error seems appear
Same i got reboot after 5 seconds of freeze, and the the blue screen appears then reboot instantly.
