### ISSUE TITLE
Reduce fan speed adjustment step

### ISSUE THREAD

**Issue by GImDX** [BartoszCichecki/LenovoLegionToolkit#1490]
### Version

2.24.2

### OS

Windows 11 21H2

### Device

Legion Y9000P IAH7H

### Is your feature request related to a problem?

Under the current version, the fan speed adjustment is divided into 10 levels (0~10), which is perfect in most cases, but for some situations that require fine adjustment, such as level 5 corresponds to 2800rpm, but level 6 is 3500rpm, the fan noise is increased by almost 10 decibels, I would prefer to adjust to 3000rpm, but it is not possible in the current version.

### How would you like the problem to be solved?

The fan speed adjustment level is more subdivided, such as 0~100

### What alternatives have you considered?

LegionFanControl, but direct access to EC, not a good choice.

**Comment by Ace-Radom** [comment]
I'm not really sure since my device doesn't support customizing fan curve, but as I know if you want to change fan speed like that without a ring0 method is impossible. How fan levels & fan speed are corresponded is controlled by EC that's why apps like LegionFanControl access directly to EC I guess, and as bc said somewhere, such function won't be added to llt due to security reason.

**Comment by Ace-Radom** [comment]
You may also check #696 and #408.

**Comment by GImDX** [comment]
Thank you very much for your reply. It seems that this issue has been raised several times, but due to the design of Lenovo, we can't solve it.
