### ISSUE TITLE
Error when assigning power plans to LLT

### ISSUE THREAD

**Issue by miodzicho** [BartoszCichecki/LenovoLegionToolkit#1498]
### Version

2,24,2

### OS

Windows 11 23H2

### Device

Legion 5 Pro 16ARX8

### BIOS version

LPCN56WW

### What is wrong?

Error windows apears when assigning Windows plan to LLT, LLT crashes after.

### What did you try already?

reinstalled, rebooted.

### How to reproduce the bug?

open settings in LLT
go to Windows power Modes
Change assignation of any plan
<img width="820" alt="Bildschirmfoto - 2024-11-21 09-45-43" src="https://github.com/user-attachments/assets/0f9838cb-c183-4e0f-bc5e-b285626eedf2">

### What is the behavior that you expected?

Plan should be assigned with error or crash

### Logs

[error_2024_11_21_08_46_23.txt](https://github.com/user-attachments/files/17842594/error_2024_11_21_08_46_23.txt)

**Comment by BartoszCichecki** [comment]
This error comes from Windows - it basically means that a power plan couldn't be set. Since you are changing settings for Windows Power Modes, the most likely reason is that you do not have the default "Balanced" power plan.

You can try resettings power related settings in Windows as described in [readme](https://github.com/BartoszCichecki/LenovoLegionToolkit?tab=readme-ov-file#windows-power-plans--windows-power-mode). If that doesn't help, reopen the issue.
