### ISSUE TITLE
Triggers AC power connected and game started/stopped do not work

### ISSUE THREAD

**Issue by nicktodorov** [BartoszCichecki/LenovoLegionToolkit#1520]
### Version

2.24.2

### OS

Windows 11 Pro 24H2 26100.2605

### Device

Legion 5 16IRX9

### BIOS version

NMCN28WW

### What is wrong?

Triggers AC power connected and Game running/closes do not work. When try run now, all steps execute correctly. But it never auto triggers.
At the same time, AC disconnected wokrs without issues.

### What did you try already?

tried to reinstall app, tried to delete and recreate actions, tried to change/edit steps, but nothing helps them trigger.

### How to reproduce the bug?

1. Configure to change power plan to Balanced when connecting AC.
2. Confugire to change powerplan to Quiet when disconnecting AC.
3. Confugire to change powerplan to Performance whengame starts.
4. Confugire to change powerplan to Balanced when game close.
Experiment with plugging AC charger or Starting/stopping game.

### What is the behavior that you expected?

I expect all actions to work as configured. And to have power plan automatically changing based on the configured actions.
[log_2024_12_17_14_17_17.txt](https://github.com/user-attachments/files/18167056/log_2024_12_17_14_17_17.txt)

### Logs

[log_2024_12_17_14_17_17.txt](https://github.com/user-attachments/files/18167057/log_2024_12_17_14_17_17.txt)

**Comment by BartoszCichecki** [comment]
The logs that you uploaded return 404 please upload again. 

Also, which game? Did you read the readme?

**Comment by nicktodorov** [comment]
[log_2024_12_17_14_17_17.txt](https://github.com/user-attachments/files/18168273/log_2024_12_17_14_17_17.txt)
I think now only plugging AC charger is not working. Somehow games triggers started working.

**Comment by BartoszCichecki** [comment]
According to the log you are using low wattage AC adapter. In this case you need to use the low wattage AC adapter connected trigger.

**Comment by BartoszCichecki** [comment]
If that is the case I suggest doing the EC reset procedure - instructions can be found on Discord server linked in readme. 
EC reset might help to fix this, but otherwise there isn't anything I can do about it, since your laptop reports wrong info.

**Comment by nicktodorov** [comment]
I made EC reset and there is no change.
But are you sure this is the case? How can the automation "think" it is low power charger, if the Toolkit itself in the battery tab show it as the regular charger?

**Comment by BartoszCichecki** [comment]
Here are pieces of log that show what type of charger was connected:

```
  407: [17/12/2024 14:17:35.299] [27] [PowerStateListener.cs#83:SystemEvents_PowerModeChanged] Event received: StatusChange
  408  [17/12/2024 14:17:35.312] [31] [Power.cs#50:IsAcFitForOc] Mode = 0
  409  [17/12/2024 14:17:35.325] [31] [Power.cs#67:IsChargingNormally] Mode = 2
  ...
  416: [17/12/2024 14:17:35.360] [27] [PowerStateListener.cs#83:SystemEvents_PowerModeChanged] Event received: StatusChange
  417  [17/12/2024 14:17:35.361] [39] [Power.cs#67:IsChargingNormally] Mode = 2
  418  [17/12/2024 14:17:35.374] [7] [Power.cs#50:IsAcFitForOc] Mode = 0
  ...
  587: [17/12/2024 14:17:42.248] [27] [PowerStateListener.cs#83:SystemEvents_PowerModeChanged] Event received: StatusChange
  588  [17/12/2024 14:17:42.260] [38] [Power.cs#50:IsAcFitForOc] Mode = 0
  589  [17/12/2024 14:17:42.277] [38] [Power.cs#67:IsChargingNormally] Mode = 2
```

Here you can see three events where Windows reported power status change. For example you plugged in, removed and plugged in AC adapter. On all three you can see that EC reports that AC adapter is not fit for OC (aka low power adapter) which happens when either no AC adapter is connected or if EC thinks this is a low power adapter.

There are other occurrences in the log where EC reports that AC is fit for OC on lines 37, 120, 136, 279, 328, 353, 624 and 645. However, automation triggers when Windows reports power status change and at this time your laptop reports wrong values.

Since this is the only report like this so far, this would indicate that this is some sort of abnormality in the way your EC reports AC status. Could be a bug in BIOS or something else. The point is LLT cannot tell at the time when Windows notifies power status change that a proper AC adapter is connected, hence why Action does not trigger.

**Comment by nicktodorov** [comment]
Thank you for the detailed explanation.
Any suggestions what can I do to fix this? 
Change some settigns in Windows/BIOS? Reinstall something? Wipe drive and make clean install following Discord guide? (I would love if possible to avoid this radical and time consuming option)
Or even maybe some hardware issue with the laptop and return for warranty?

**Comment by nicktodorov** [comment]
BTW new finding - while I was browsing the discord reading guides, laptop was plugged to the original charger, but since Toolkit did not recognized it as you decribed, it was still on 60Hz and Quiet mode (what action when disconnect AC does). So just now, battery got to 100%, charging stopped and suddently the action triggered and worked as it shoud. Really weird.

**Comment by BartoszCichecki** [comment]
Hey, sorry for long response time. 

Issues like this are very difficult to "fix". Reinstalling Windows will most likely not help. You try to reinstall the Lenovo Energy driver which should be somewhere on the Lenovo support page.

Otherwise if resetting EC does not help, I don't know if there is anything we can do. Claiming warranty will be difficult unless you can demonstrate the problem using Lenovo software only - I am not sure if you can even do it. Still, they will most likely ask you to reinstall everything and in general they might just say it's a "software issue" and refuse warranty.

Sorry, but that's not the best news.
