### ISSUE TITLE
I need a boot screen customization feature

### ISSUE THREAD

**Issue by cgbb0** [BartoszCichecki/LenovoLegionToolkit#1523]
### Version

2.24.2

### OS

windows 11 24H2

### Device

G5000 APH8

### Is your feature request related to a problem?

I want to use LLT on a pure Windows, I need the boot screen customization in Lenovo PC Manager, but I don't want to install Lenovo PC Manager.
![image](https://github.com/user-attachments/assets/a217394d-3b23-4262-881e-a7f4560a4209)

### How would you like the problem to be solved?

I'd like to be able to modify and preview the boot screen in LLT

### What alternatives have you considered?

I haven't found a non-Lenovo official solution yet

**Comment by BartoszCichecki** [comment]
Gen 8 and 9 are not supported when it comes to boot logo change.

This issue has been discussed before. Please check closed issues and readme before opening new ones. 

Of course if someone finds a way to implement it I am happy to accept PRs, but making more issues "because you need it" is not helping.
