### ISSUE TITLE
[FEAT]: Add performance monitor

### ISSUE THREAD

**Issue by Godl1nk** [BartoszCichecki/LenovoLegionToolkit#179]
Add a CPU, GPU, RAM statistics monitor, this is something i wish lenovo vantage had. 
A fancy page with hardware usage, temps, clocks and stuff.

![image](https://user-images.githubusercontent.com/47373157/186313555-22551e70-65d4-4232-93b7-d5d20f957d6c.png)

**Comment by BartoszCichecki** [comment]
There are already good tools doing this like HWinfo for example. I am not sure if this is actually worth implementing and duplicating the features.

**Comment by Godl1nk** [comment]
hmm to make it all in one is better dont u think so ?
also idk if its me the application feels abit lagy, app only not the system

**Comment by BartoszCichecki** [comment]
No, I don't actually. Basic information can already be seen even in Windows Task Manager, other tools provide more complete information and options like in game OSD.

But again, if it is requested more I'll take a look at this. At the moment this seem to be a gimmic, that doesn't really add anything.

**Comment by Oblivious02** [comment]
Just use MSI Afterburner mate, I'm not convinced of making this app heavier with it at all times when I don't need it.

**Comment by AceAsket** [comment]
I would like to see the temperature and speed of the coolers, as there is an adjustment in the application

**Comment by jojo2massol** [comment]
I think we should apply the [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) ("Keep it simple, stupid!") for this. Lenovo Legion Toolkit is more a software to trick some options, not a sensor monitoring software. Something good for that is [LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor), but I must admit that the interface is getting old. 
Afterwards, it's up to you to create a Fork and implement this, but I imagine that it won't be easy to create the gauges and graphics...
What could really be nice would be to implement what [LegionFanControl](https://www.legionfancontrol.com/) is doing, but since [@RodPad](https://github.com/Rodpad) haven't published the source code yet, I don't open a feature request for this.

**Comment by GImDX** [comment]
I am agree with adding the feature, at least as a plugin. Some new model such as IAH7H can not be monitored nether CPU and GPU fan speed by HWINFO.

**Comment by nadtorus** [comment]
I personally don't really agree adding this feature. Like Bartosz said, it's just a gimmick and adds no essential functionality imo, it will use CPU more (that's why LLT was made in the first place, a light version of vantage, and even better), better allocate that for other feature that actually contributes to laptop configurations/settings. It will change the LLT 'personality', imo.

But, if it could be made with negligible-to-zero addition to CPU usage, I might be agree.
