### ISSUE TITLE
Exposing battery temp and other battery info

### ISSUE THREAD

**Issue by djoris** [BartoszCichecki/LenovoLegionToolkit#20]
I would love to see the data for the battery in this app.
The Lenovo Vantage software exposes stats like temperature, health (max capacity, charge cycles), voltage and 'watt' which I believe is the charging speed.
Screenshot: https://bayimg.com/325c24aec5f7659a5bc4cdff51280244851d558d.jpg
Original question: https://www.reddit.com/r/LenovoLegion/comments/qb88d2/comment/hk6t0qt/?context=3

**Comment by younyokel** [comment]
Would be useful.

**Comment by BartoszCichecki** [comment]
Added to the list. I'll see what can be done - not sure which interface is used to get this info though at the moment.

**Comment by BartoszCichecki** [comment]
So, after looking into this, it seems like Lenovo is pulling this data straight from the energy driver. Pretty much everything except for temperature is accessible through WMI, but I understand that temperature is what you would like to see the most.

I don't know the specifics of how to get temperature from energy driver at this point, so that's why I will label this as `help wanted` - maybe someone will be able to help.

**Comment by Eitsop** [comment]
Hi, maybe already addressed - I'm not sure, but I have a project (https://github.com/Eitsop/Battery/) that queries the battery state. It does  have temperature present but my laptop does not support the function. You might have more luck! It uses the DeviceIoControl methods in C and I've wrapped them up into a managed set of classes. 

var powerState = new PowerState();
var temp = powerState.Battery.First().Temperature;

Then to refresh:

firstBattery.Refresh();
temp = powerState.Battery.First().Temperature;

Hopefully it'll be useful. It's not as well presented as WMI, and just exposes the basic data received from the battery driver.

**Comment by BartoszCichecki** [comment]
Will definitely try this out! It is not a problem that it's not WMI :) If it works do you plan to expose this on nuget.org or is it ok if I just copy & paste your code into this repo? (and mention you in credits of course)

**Comment by Eitsop** [comment]
Feel free to copy/paste into the code. It was code I wrote a while ago and was just hanging round until I saw a help wanted, so I thought it best to share. I think it's a bit specialised for nuget, so, please help yourself. If the MIT is too restrictive I can change the license.

**Comment by BartoszCichecki** [comment]
Unfortunately at least on the 5 Pro, battery temperature is handled in some custom way, because it just shows `0` :(

**Comment by mind12** [comment]
I would like to add a feature request related to this battery info output.
It would be a cool feature if we could let conservation mode charge the battery up to 80%. 
I imagine a conservation mode 80% button where conservation mode is applied as soon as the percentage reaches 80%.
Do you think it's possible? If you can get the charge percentage it would be easy to code this right?

Thank you for your dedicated work!

**Comment by BartoszCichecki** [comment]
@mind12: I am not sure if the energy driver supports this sort of setting. And if it doesn't, then this would have to work on a software level which means Toolkit would have to change battery mode when charge reaches a certain level. The problem is if you put the laptop to sleep, then Toolkit will not have the chance to change this settings and battery will charge to 100% anyway. I am not a fan of this type of solution that I know will be broken as a concept.

Charging the battery to 80% isn't really "conservation mode" anymore. Lithium based battery should be stored at around 50% of charge, so the default 60% is already the upper limit. Also, stored, means weeks or maybe months, if you use the laptop on battery like once a week at least, just charge it to 100%. Battery will go bad over time regardless of what you do.

**Comment by mind12** [comment]
> @mind12: I am not sure if the energy driver supports this sort of setting. And if it doesn't, then this would have to work on a software level which means Toolkit would have to change battery mode when charge reaches a certain level. The problem is if you put the laptop to sleep, then Toolkit will not have the chance to change this settings and battery will charge to 100% anyway. I am not a fan of this type of solution that I know will be broken as a concept.
> 
> Charging the battery to 80% isn't really "conservation mode" anymore. Lithium based battery should be stored at around 50% of charge, so the default 60% is already the upper limit. Also, stored, means weeks or maybe months, if you use the laptop on battery like once a week at least, just charge it to 100%. Battery will go bad over time regardless of what you do.

OK, convinced by the first part that putting the notebook to sleep would prevent it to work, so just dump this.
