### ISSUE TITLE
[BUG]: Latest version 2.6.3 refuses to launch on unsupported laptops

### ISSUE THREAD

**Issue by v-marinkov** [BartoszCichecki/LenovoLegionToolkit#312]
### Version

2.6.3

### OS

Windows 11 Home 22621.675

### Device

Yoga Slim 7 Pro 16ACH6

### BIOS version

N/A

### What's wrong?

2.6.2 and below work very well on my Yoga Slim but updating to 2.6.3 results in getting a "Device is not supported" error which only has OK and no Continue, so the Toolkit doesn't launch.

### How to reproduce the bug?

See above

### What is the behavior that you expected?

The Toolkit should work just like before

### Logs

N/A

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
LLT does not support other laptops than Legion and Ideapad Gaming.

**Comment by BartoszCichecki** [comment]
Next version will respect the --skip-compat-check argument, but that doesn't change the fact that LLT shouldn't be used on other laptops for many reasons.

**Comment by v-marinkov** [comment]
> Next version will respect the --skip-compat-check argument, but that doesn't change the fact that LLT shouldn't be used on other laptops for many reasons which may include for example soft bricking battery driver.

When does soft bricking the battery driver occur and what does it entail? Is it irreversible? I benefit greatly from LLT as Vantage is awful and drains my batter during sleep.

It happened to me before that LLT broke the battery conservation mode (charge up to 60%) and it disappeared even from the BIOS. Installing Vantage fixed it, so now I have Vantage installed but ask LLT to disable it, instead of me uninstalling it.

**Comment by BartoszCichecki** [comment]
It is a lottery. Basically LLT is sending some "codes" to the Energy driver, and because not 100% of Vantage was ported to LLT, some devices might expect different codes for stuff like Fn Lock, Conservation mode etc.

What happens if an unexpected code is sent to a driver? I have no idea: sometimes nothing happens, sometimes you get a blue screen, sometimes your laptop just turns off immediately, sometimes you might need to reset EC or BIOS and if you are unlucky the IC controlling the battery charge might just brick.

It really is a lottery, this is why LLT is more aggressive in checking for device compatibility, because I can see people are using it on devices that LLT obviously wasn't supposed to run on. And despite of all warnings and "use at your own risk" stuff, I don't want someone to accidentally brick their device.

**Comment by BartoszCichecki** [comment]
And it's not only battery related stuff - most Lenovo laptops have fairly "generic" WMI methods sending stupid data as parameters over WMI can also cause some funky behavior.
