### ISSUE TITLE
Change Refresh Rate feature

### ISSUE THREAD

**Issue by chenm0416** [BartoszCichecki/LenovoLegionToolkit#39]
Is it possible to add a switch to change screen refresh rate because FN+R does not currently work for the Intel based laptops?

**Comment by BartoszCichecki** [comment]
I will be looking into refresh rate switching soon. On my laptop (AMD + nVidia), Fn+R works fine even with Vantage disabled. It seems like Fn+R is handled through Lenovo Fn Keys software which is not disabled by Toolkit.

**Comment by chenm0416** [comment]
Yeah, it has nothing to do with Lenovo Vantage or Toolkit. FN+R has just always been broken on all Intel systems to my knowledge.

**Comment by BartoszCichecki** [comment]
Ah, I see! Now it makes more sense. I probably won't be able to intercept Fn+R because it is handled on a very low level by Lenovo and I haven't found a way to "listen" to that. Fn+Q is the same, but it also invokes an WMI event and that's why power plan switching could be done.

BUT as I said, I will be working on adding refresh rate switch to Toolkit so maybe that will be enough to have quicker access to it?

**Comment by chenm0416** [comment]
Yes, that would be fantastic!
