### ISSUE TITLE
[COMPATIBILITY]: Can Custom Mode be enabled for Legion 7 Slim (2022) bios KFCN30WW?

### ISSUE THREAD

**Issue by niclasmattsson** [BartoszCichecki/LenovoLegionToolkit#396]
### Version

2.6.5

### OS

Windows 10 22H2 build 19045

### Device

Legion S7 16ARHA7

### Which features of the application did you test?

Custom Mode

### Which features of the application do not work as expected?

Custom Mode

### Additional information

Despite having the 2022 version of the Legion 7 Slim, my bios (KFCN30WW) is not in the supported list for Custom Mode. Is it possible to enable support for this model? If it can't be done, would you mind explaining why? (If my machine is different from other 2022 models I'm just curious in what way it's not like the others.)

**Comment by BartoszCichecki** [comment]
It's not added because no one tested if it's compatible :)

Below you can find a build that enables Custom mode on KFCN30WW and higher. Test it and report back. If all is fine, next version will support it.

[LenovoLegionToolkitSetup_kfcn.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10049732/LenovoLegionToolkitSetup_kfcn.zip)

**Comment by BartoszCichecki** [comment]
Hey @niclasmattsson, if you could get the testing done withing a day or two, that would be great. I am planning on releasing a new version soon.

**Comment by niclasmattsson** [comment]
Thanks for the quick response and sorry for the delay on my part. I had a problem with Windows Defender blocking the download after detecting a Trojan. I disabled real time protection so I could download it and run it through Virustotal. Although I'm fairly sure it's just a false positive, our IT department won't allow to install anything that triggers Defender. So sadly I can't test this until Defender lets it through, but at that point I'd be happy to be your guinea pig. Here's the signature:

https://www.virustotal.com/gui/file/9457ddb65b3394213a2df42e8a0395b07544624e43a1b14b7259fca265622420?nocache=1

**Comment by BartoszCichecki** [comment]
It has been a known issue sadly, and there isn't anything I can do, because I will not pay hundreds of dollars for a code signing certificate to silence defender. I guess this will need to wait until someone else can test.

**Comment by niclasmattsson** [comment]
Too bad. Just a thought: I don't recall triggering Defender when I installed the latest full version of Legion Toolkit. Could it be something in your test build that triggers it? And is it just a matter of flipping a flag for this bios version to enable support? If so, would it be possible to enable that flag for this particular bios without testing? Then I could test it and report here.

**Comment by BartoszCichecki** [comment]
This exe was build of latest master, so whatever changes are there (mostly support for Spectrum RGB keyboards) will also be there in next release. When you click update in LLT you will get exactly the same exe as if you would download it from GitHub directly, because update just downloads the latest installer from here. Defender is overly sensitive to unsigned exe files downloaded via browser, which is probably why it stays quiet when you update :)

But I can't just enable it, there where different problems on different BIOS versions (like locking the CPU at 0.4GHz until reboot), so until someone verifies it I can put it in the release and distribute it to 10k+ users.

You can also get the code and build the version directly if you want of course. No secrets here.

**Comment by niclasmattsson** [comment]
I understand, thanks for explaining. But consider this a warning that unless Windows Defender soon becomes more forgiving with its signatures then you may get a *lot* of people claiming that you gave them a trojan when you release the next version. :)
