### ISSUE TITLE
[FEAT]: Action for choosing GPU working mode

### ISSUE THREAD

**Issue by mooms06** [BartoszCichecki/LenovoLegionToolkit#401]
### Version

2.6.5

### OS

Windows 11 21H2 build 22000.1219

### Device

[Legion 5 15IAH7](https://psref.lenovo.com/Detail/Legion/Legion_5_15IAH7?M=82RC0004FR)

### feature request

An action to be able to change GPU mode (Hybrid, Auto, etc...) would be great.

**Comment by BartoszCichecki** [comment]
What scenario do you have in mind?

**Comment by mooms06** [comment]
Being able to change the GPU mode when plugged/unplugged.

**Comment by BartoszCichecki** [comment]
How would this work if Hybrid mode change require a reboot?

**Comment by AlaDragon** [comment]
I believe he is talking about Advanced Optimus as I have the same request, I wish to be able to switch from dGPU to Optimus or Auto Select.
This feature would be great in reducing energy consumption while on battery without having to do it manually each time.

**Comment by BartoszCichecki** [comment]
> I believe he is talking about Advanced Optimus

I see. Well I agree, but there is always a "but". I don't know of any API that would allow 3rd part apps to control these settings. So at the moment, it qualifies as "can't be done".

**Comment by mooms06** [comment]
Can't you "reverse engineer" how Vantage does it ?

**Comment by BartoszCichecki** [comment]
Vantage does not do use that settings. That's why I was asking which one do you mean.

Hybrid options in Vantage are completely separate from Advanced Optimus, so please explain what do you mean.

**Comment by AlaDragon** [comment]
There seems to be a hidden option that only shows in some (I think 2022) Legion models. in the Vantage software, these laptops have a toggle next to the Hybrid mode that allows you to select what type of Advanced Optimus you like to run, [here's a screenshot that shows the options in Vantage.](https://preview.redd.it/hello-can-you-please-explain-these-modes-to-me-like-im-5-v0-gxpszokxbet91.png?auto=webp&s=884ecb26b6fe12b0da3bb145174858e605d095f5)  
It would be great if such feature was added to LLT to work with the rest of the models that seem to have this option hidden even if the laptop supports Advanced Optimus.

**Comment by BartoszCichecki** [comment]
> here's a screenshot that shows the options in Vantage.

Again, this is not Advanced Optimus settings.

**Comment by mooms06** [comment]
I don't know what's advanced Optimus, I'm talking about an action to switch between the three hybrid mode showed in your capture.

**Comment by BartoszCichecki** [comment]
It is super confusing what do you want to change @mooms06 because you indicated a gen 6 Legion in this ticket. Currently Advanced Optimus doesn't have any 3rd party API and in Vantage you have only a simple Hybrid on/off switch which requires restart, so there is no point in adding this to actions. Gen 6 devices don't support these modes that @AlaDragon posted.

**Comment by AlaDragon** [comment]
I think on the 2022 models it's called 'GPU working mode' and it shows up as list to choose from like [this](https://static.tweaktown.com/content/1/0/10145_30_lenovo-legion-5-pro-2022-gaming-laptop-review_full.png) in Vantage, however on 2021 models it shows up as 'Hybrid mode' with no choices like in [this](https://www.yugatech.com/wp-content/uploads/2021/04/legion-5-pro-vantage_1.jpg).
I guess what I'm trying to say is would it be possible to add the option of choosing GPU working mode to LTT instead of just choosing Hybrid mode on or off ?

**Comment by mooms06** [comment]
> It is super confusing what do you want to change @mooms06 because you indicated a gen 6 Legion in this ticket. Currently Advanced Optimus doesn't have any 3rd party API and in Vantage you have only a simple Hybrid on/off switch which requires restart, so there is no point in adding this to actions. Gen 6 devices don't support these modes that @AlaDragon posted.

My bad, it's a gen7/2022 Legion, with (12500H), here is the full specs: https://psref.lenovo.com/Detail/Legion/Legion_5_15IAH7?M=82RC0004FR
I made a mistake when copying the model number apparently, I will edit it.

**Comment by BartoszCichecki** [comment]
OK, great, thanks for clearing this up. Now, when you talk about a scenario of changing the GPU working mode when plugged in/not plugged in, the things is as follows:

1. If you want to switch from any of the hybrid modes to dGPU mode restart is still required even on gen 7, so it doesn't make sense to add it to actions.
2. If you want to switch between the 3 Hybrid modes, I also don't see a reason, because you should just choose Hybrid-Auto which will automatically eject dGPU when you unplug AC adapter assuming that it can be ejected (no apps are using it for example).

Is there any scenario that I am missing here?

**Comment by AlaDragon** [comment]
Do these [Nvidia settings](https://nvidia.custhelp.com/rnt/rnw/img/enduser/aid_5097_01.png) do the same thing as these [settings in Vantage](https://preview.redd.it/hello-can-you-please-explain-these-modes-to-me-like-im-5-v0-gxpszokxbet91.png?auto=webp&s=884ecb26b6fe12b0da3bb145174858e605d095f5) ? If yes, then the Gen6 laptops should be able to support the newer Vantage GPU modes because that Nvidia settings screenshot is from a Legion 5 Gen6 laptop.

**Comment by BartoszCichecki** [comment]
> Do these [Nvidia settings](https://nvidia.custhelp.com/rnt/rnw/img/enduser/aid_5097_01.png) do the same thing as these [settings in Vantage](https://preview.redd.it/hello-can-you-please-explain-these-modes-to-me-like-im-5-v0-gxpszokxbet91.png?auto=webp&s=884ecb26b6fe12b0da3bb145174858e605d095f5) ?

No, they are different, unrelated settings.

**Comment by mooms06** [comment]
> OK, great, thanks for clearing this up. Now, when you talk about a scenario of changing the GPU working mode when plugged in/not plugged in, the things is as follows:
> 
>     1. If you want to switch from any of the hybrid modes to dGPU mode restart is still required even on gen 7, so it doesn't make sense to add it to actions.
> 
>     2. If you want to switch between the 3 Hybrid modes, I also don't see a reason, because you should just choose Hybrid-Auto which will automatically eject dGPU when you unplug AC adapter assuming that it can be ejected (no apps are using it for example).
> 
> 
> Is there any scenario that I am missing here?

Because Hybrid and Hybrid auto are causing freezes just after the UAC popup (I think the system is switching GPU automatically), Hybrid-iGPU only is not affected, but I would like to be able to change it automatically or with a shortcut, hence the action. Of course changing between dGPU only and iGPU only on the fly would be ideal, but it's sadly not possible.

**Comment by BartoszCichecki** [comment]
> Hybrid and Hybrid auto are causing freezes

That sounds like a driver related issue to me. I have a Legion 7 gen 7 myself and I am running it exclusively in Hybrid or Hybrid-Auto modes all the time and I do not experience any freezes regardless of AC adapter connected or not or external screen connected or not (any combination).

Adding an action to switch these modes  will be confusing, because for example Hybrid-Auto already behaves like an "action" and on top of that switch of the mode is not guaranteed (because dGPU might be in use).

**Comment by mooms06** [comment]
The mouse cursor freeze is just after the UAC popup, an only for about a second or less, but it's enough to be noticed. I had the same issue with my previous Legion, a gen 6 AMD, so I don't think it's a driver issue.

If you think it's a bad idea that's OK.
