### ISSUE TITLE
Change power mode automatically when a process is running

### ISSUE THREAD

**Issue by dannk12** [BartoszCichecki/LenovoLegionToolkit#46]
I5 10300h+1660ti/win10, авто смена режимов производительности(например игры) не проводит в красный режим, вообще стоит на месте. Работа в фон активности в Винде работает и включена.

**Comment by BartoszCichecki** [comment]
I do not speak russian. Let's keep the discussions here in english :)

**Comment by dannk12** [comment]
Auto change of performance modes blue \ white \ red does not work

Windows 10 Background activity enabled

**Comment by BartoszCichecki** [comment]
What do you mean by auto change?

**Comment by dannk12** [comment]
How lenovo vontage does it, when you enter the game, it goes to red (performance) and back when you exit the game

**Comment by BartoszCichecki** [comment]
Ah, I see. This is not supported. Vantage monitors processes running on the background and when it detects a process that is on the list, auto changes power mode.

I'll keep this in mind, but it's not very high on the priority list at the moment.

**Comment by dannk12** [comment]
I hope it will be available sometime, at least when you manually select a process in the list.
Thanks for your hard work.

**Comment by BartoszCichecki** [comment]
Can you describe more in detail on how this feature is supposed to work? I don't have any compatible software that would trigger this on my machine.

I understand it should be more or like this:
1. You start process.exe
2. Laptop automatically switches to Performance mode (RED)
3. You stop process.exe
4. Laptop automatically switches back to the last used mode.

What happens when you try to Fn+Q while process.exe is running? Does it allow you to go out of Performance mode?

**Comment by seshavaraaj** [comment]
- it stores the current mode and goes to performance mode if it detects directX or fullscreen activities
- you can change it when the directx or fullscreen activity is going on by pressing fn + q
- it will return to the power state it was on before the directx or fullscreen activity started

**Comment by BartoszCichecki** [comment]
This can be done now with actions.
