### ISSUE TITLE
Prevent Screen Brightness Resetting/Maxing After Sleep/Hibernate

### ISSUE THREAD

**Issue by Byrkoet** [BartoszCichecki/LenovoLegionToolkit#48]
- MODEL: `16ACH6H`
- BIOS: `GKCN46WW`
- DRIVERS: `Lenovo Fn and Function Keys`, `Lenovo Energy Management`, `WLAN`, `AUDIO`, `BT`, `NVIDIA 497.09`

After sleep, screen resets to max brightness (100%). Brightness slider will be set correctly to previously set value, but only after moving the slider will the screen brightness adjust itself. Perhaps this tool could apply `powershell.exe -(Get-WmiObject -Namespace root/WMI -Class WmiMonitorBrightnessMethods).WmiSetBrightness(1, <PreviousValue>)` or whatever the correct method is.

For some it might also be useful if the tool could allow resetting power plans: by applying `Legion_Balanced.pow`, `Legion_Quiet.pow`, and `Legion_Performance.pow` configs, while removing the current profiles, which I believe is default Vantage behavior. While I prefer to have a single power profile, the expected behavior when `FN+Q` is to switch the preset power profiles.

Not sure whether this issue is resolved by proper configuration or it's a Windows 10 bug specific to me. I'm never installing Vantage or any other bloatware to find out tho.

**Comment by BartoszCichecki** [comment]
The problem with brightness does not appear on my machine, so I will not be able to implement this. It also seems like it is an issue with drivers/setup on your machine, not a general issue.

Regarding default power profiles. I do not think this is a good idea, since I do not have time and resources to make sure that the power plans are correct and up to date. It is impossible to say when and if Lenovo will modify them for all (or some) models. I don't even know if the custom Lenovo profiles are the same for all supported laptops. This is why Toolkit by default assumes that these power profiles are present.

#38 introduces possibility of setting custom profiles for Power modes, so I guess you will be able to configure it a little bit more for your needs.

It is worth mentioning that I am running a stock Lenovo Windows install. It doesn't really contain any bloatware (except McAffee which is easy to remove), so I never bothered installing Windows from scratch. I do my best to account for setups like yours where Vantage was never installed, but I am not able to cover this scenario on my machine.
