### ISSUE TITLE
If you switch the profile to "Red" and then disconnect it from the outlet, the program will still read the status as "Red", although it is not available when running on battery power. At the same time, the "Performance" checkbox is active and even switches windows profiles, but not the laptop.

### ISSUE THREAD

**Issue by ateplih** [BartoszCichecki/LenovoLegionToolkit#51]

**Comment by BartoszCichecki** [comment]
This will not be fixed.

This is the same behaviour as Vantage where it is possible to set laptop into Performance mode even on battery where power profile is changed and Lenovo's WMI functions are reporting that current mode is Performance.

It seems that this change from Red to White LED when on battery is done in BIOS/UEFI and is not exposed in Windows/WMI correctly by Lenovo.

**Comment by ateplih** [comment]
Maybe you can activate the reading of the mode state and reassign the power scheme using the windows event log?

**Comment by BartoszCichecki** [comment]
The problem is that the reading from Lenovo WMI also indicates that active power mode is Performance when you are on battery (even though the LED is white).

Later down the road I plan to introduce some automation that will among other things respond to AC connect/disconnect. It is quite big so don't expect it too quick ;) But once it is here I imagine it will be possible to change power modes and refresh rate automatically when AC is connected/disconnected. #36 also requests running custom scripts which also will be there.
