### ISSUE TITLE
[FEAT]: Remap function of Action Keys (the secondary action on the Fn keys)

### ISSUE THREAD

**Issue by zwresn453** [BartoszCichecki/LenovoLegionToolkit#515]
### Version

2.8.1

### OS

Windows 11 21H2

### Device

Legion 7 16ACHg6

### Is your feature request related to a problem?

Not a bug report. Let me know, if that's not what that means.

### How would you like the problem to be solved?

TLDR: While some Action Keys send a signal that is remappable, some others send a key combination such as "Win+P" and therefore can't be remapped by any other software that I know of. Being that LLT is specially designed to access Lenovo Legion firmware, I am hopeful that you know of a way that LLT could intercept/reprogram these keys, to a user-defined action, which could be very useful, especially on devices missing media control buttons.

Some of the action keys (the secondary actions on the function keys) are useless and would be nice to be remappable (such as the Win+P and Alt-Tab buttons). While some are remappable via remapping software, some others are not. I used Microsoft PowerToys to test each action key:

Some keys send signals that are remappable by remapping tools, such as Calculator (detected as "Start App 2");

But the Project (Win+P) and Alt-Tab Action Keys seem to send their literal combinations (Win+P and Alt+Tab), meaning they cannot be remapped by PowerToys (as remapping them would cause the Win, P, Alt, and Tab keys to not work). If the signal could be intercepted by LLT and changed to another signal, such as Play/Pause or to launch a script, I could see this being very useful for many people. However, whether this is possible would depend on technical information that I do not have. Because LLT is specifically designed to interact with the Lenovo Legion BIOS, I am hopeful that you know of a way that the software could somehow accomplish this.

### What alternatives have you considered?

Key remapping software and AHK, which do not work because it seems that the BIOS is sending a certain key combination to Windows (Win + P for example), and the remapping software cannot detect whether the user, or BIOS pressed the keys. 

AHK, which also doesn't work for the same reason.

**Comment by zwresn453** [comment]
I have some other feature ideas too. Should I post them all here so you can see them all at once, or should I make a new feature request for each of them?

Thanks for your time

**Comment by BartoszCichecki** [comment]
Let me deconstruct this a little bit:

> While some are remappable via remapping software, some others are not.
> Project (Win+P) and Alt-Tab Action Keys seem to send their literal combinations (Win+P and Alt+Tab), meaning they cannot be remapped by PowerToys

Some simply cannot be remapped, so if PowerToys or Autohotkey can't do it, I also won't be able to.

> LLT is specifically designed to interact with the Lenovo Legion BIOS

That only applies to Fn key combinations because those are the only "handled" by BIOS and most of them can't be remapped anyway.

> BIOS is sending a certain key combination to Windows (Win + P for example)

Not BIOS, it's a Windows shortcut

In general key remapping is not something LLT will do - there are very good tools which you mentioned that already do what is possible.


Regarding your second comment: One feature per issue please, but look through already closed issues so you don't spend time on things that already have been discussed. And just like with key remapping: LLT is a Vantage replacement, not a swiss army knife that should do everything; so keep this in mind.
