### ISSUE TITLE
[FEAT]: G9CN30WW support in Custom Mode

### ISSUE THREAD

**Issue by Glimspe** [BartoszCichecki/LenovoLegionToolkit#526]
Enable custom mode

### Version

2.8.1

### OS

Windows 10 Home 21H2

### Device

Legion 5 15ACH6A /R7000P 2021A

### Is your feature request related to a problem?

none

### How would you like the problem to be solved?

It would be nice to have custom mode on the laptop too.
Machine type: 82NW
BIOS: G9CN30WW

Willing to test and troubleshoot, if that helps.

### What alternatives have you considered?

none

### Additional information

none

**Comment by BartoszCichecki** [comment]
[LenovoLegionToolkitSetup_g9cn.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10550159/LenovoLegionToolkitSetup_g9cn.zip)

Here you go a build to test. Let me know about the results.

**Comment by JINGYUWUQI** [comment]
Hey, The custom mode works exactly as expected.And I think if you can deactivate discrete AMD GPU(RX6600M,AMD Radeon™ RX 6600M Mobile Graphics),by [PnPUtil Command Syntax](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/pnputil-command-syntax), for example  : pnputil /disable-device <id>.Because I don't konw how you Deactivate discrete GPU for nvidiva,so I search this method. Thank you for all the hard work. It's a great piece of software.

**Comment by Glimspe** [comment]
But can we disable AMD gpu device interface instance by disabling the amd device's drivers..Because microsoft have provide related  instroduction.for example ,run windows powershell as administrator,then type in the code' pnputil /disable-device " instance ID",and i successfully disable this device,so i think this way is feasible.

**Comment by BartoszCichecki** [comment]
No it's not for many reason. Mostly because disabling device in device manager does not turn off the actually device.
