### ISSUE TITLE
Investigate Fn+R and Fn+F9 handling

### ISSUE THREAD

**Issue by BartoszCichecki** [BartoszCichecki/LenovoLegionToolkit#54]

**Comment by ldstein** [comment]
Just wanted to share some of my observations.

`ROOM\WMI\LENOVO_UTILITY_EVENT` will fire events on various FN key presses:

```
###############################################################################
# Utility Event Powershell Script
# -----------------------------------------------------------------------------
# KeyCodes fired on press of a Lenovo Utility Key
# -----------------------------------------------------------------------------
#  1 - FN+F9   (Smart key launcher)
#  2 - FN+Esc   (Function Lock Enabled)
#  3 - FN+Esc   (Function Lock Disabled)
#  4 - FN+PrtSc (Snip Sketch Launcher)
# 16 - FN+R     (Refresh Rate toggle)
###############################################################################
Register-WMIEvent `
    -Namespace "ROOT\WMI" `
    -query "select * From LENOVO_UTILITY_EVENT" `
    -sourceIdentifier "test_event" `
    -action {		
        $KeyCode = $EventArgs.NewEvent.PressTypeDataVal
    }
```

Refresh Rate (FN+R) and Smart Key Launcher (FN+F9) are handled by the [Lenovo Hotkeys App](https://www.microsoft.com/en-us/p/lenovo-hotkeys/9pcmmnb260tx). 

- If the Lenovo Hotkeys app is not installed or not running, pressing FN+F9 or FN+R will result in no action.
- If an external monitor is attached, pressing FN+R will not toggle the refresh rate of any monitor (looks like a bug or intentional design decision in the Lenovo Hotkeys App).
- FN+F9 and FN+R appear to have no dependencies on either the Vantage Service or ImControllerService
