### ISSUE TITLE
[BUG]: A small block over the hover box

### ISSUE THREAD

**Issue by decipher3114** [BartoszCichecki/LenovoLegionToolkit#625]
### Version

2.11.1

### OS

Windows 11 Pro Dev Channel

### Device

Lenovo IdeaPad Gaming 3

### BIOS version

EGCN40WW

### What's wrong?

![image](https://user-images.githubusercontent.com/84389932/226158590-d24e4a47-d71f-4119-b3b3-47cd1c79959d.png)

- This small block is shown over the hover box.
- The hover time is too quick. Increase it to system default or make it 400 ms.
- The hover box should be static. If the mouse is out very below, then half of the taskbar is occupied.

### How to reproduce the bug?

Just hover over the task tray icon.

### What is the behavior that you expected?

N.A.

### Logs

N.A.

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
* The black box is a Windows issue, hope it gets resolved with future updates.
* The hover time is not currently configurable in the library used (Hardcodet.NotifyIcon.Wpf) so I cannot change it for now.
* The hover box cannot be static since Windows does not provide information about position of tray elements.

If anything above changes in the future I will come back to this ticket.
