### ISSUE TITLE
[BUG]: Crash when enabling autorun

### ISSUE THREAD

**Issue by xiaoyi2012** [BartoszCichecki/LenovoLegionToolkit#704]
### Version

2.12.0

### OS

Windows 11 home 22H2 22621.1635

### Device

legion r9000p arx8

### BIOS version

LPCN27WW

### What's wrong?

![1](https://user-images.githubusercontent.com/132508504/236044519-28d41786-80f2-40eb-b7ab-c113e44c2045.png)

A bug occurs after the setting boots

### How to reproduce the bug?

1 Settings
2 autorun
3 enabled or enabled delayed

### What is the behavior that you expected?

autorun

### Logs

[1.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11391142/1.zip)

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Please collect proper logs by following: https://github.com/BartoszCichecki/LenovoLegionToolkit#how-to-collect-logs

If the issue only appears when autorun please do the following to enable logging:
1. Go to `%LOCALAPPDATA%\LenovoLegionToolkit`
2. Create `args.txt` file in there (if you already have it edit)
3. Paste `--trace`

**Comment by xiaoyi2012** [comment]
[log.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11391340/log.zip)

**Comment by BartoszCichecki** [comment]
I can see the crash occurs because LLT is denied access to creating a task in Windows Task Scheduler (which is used for autorun). This is not an expected situation and indicates some issue with your Windows install of system configuration, so I can't help you with this issue.

Make sure that:
1. the user that you log in to in Windows has administrator rights
2. LLT is installed for that user (and not some other Administrator account)
