### ISSUE TITLE
[FEAT]: On demand backlight or timeout based keyboard backlight turn off option

### ISSUE THREAD

**Issue by sumitbhowmick** [BartoszCichecki/LenovoLegionToolkit#717]
### Version

2.12.0

### OS

Win 11

### Device

Legion 5 Pro 16ARH7H

### Is your feature request related to a problem?

Lenovo doesn't provide a timeout based keyboard backlight option in Legions. For example, Dell (used Inspiron & Latitude) has this feature for ages.
It is inconvenient to manually turn on/off backlight, and it is unnecessary power/battery wastage in between keyboard usage.

The backlight consumes about 4 watt when turned ON. Having this feature alone will add about 2-3 hrs battery life in idle/light usage without manually turning backlight on/off.

This will be very useful feature for reading articles, logs, watching movies etc. It is also hasslefree and very convenient when keyboard backlight bleed around key edges is eye straining (legion 5 Pro Gen 7).

### How would you like the problem to be solved?

In the "timeout based backlight option", the backlight should turn on when any key is pressed or touchpad is touched, provided backlight is not turned off mode.
Backlight should automatically go off automatically after a period(15/30/60sec) of both touchpad & keyboard inactivity.

As LLT provides 3 presets & off mode, following alternatives may be considered:
1. Option to enable timeout based backlight turn off across all presets.
2. Provide another preset, say timeout - only for static light option.

Preferably an option to customize timeout - 15/30/60sec should be available.
The timeout is applicable only for turning off the backlight after a period of inactivity (need not be very precise - 5 sec error of margin is okay). Backlight must turn on immediately once a key is pressed.

It is actually envisaged as on-demand backlit, as we can keep it ON forever and never worry about wasting power/battery.

### What alternatives have you considered?

There have been couple of projects in this regard, but they did not work on legion.
https://github.com/ligius-/lenovo-backlight-control
https://github.com/pspatel321/auto-backlight-for-thinkpad
https://www.autohotkey.com/

### Additional information

As per ligius project and its issues, I tried to access following DLL, but couldn't proceed much due to my lack of knowledge of powershell, DotNet and these libraries.
C:\Users\All Users\Lenovo\Vantage\Addins\IdeaNotebookAddin\1.0.2.18\IdeaNotebookAddin.dll

**Comment by BartoszCichecki** [comment]
I like the idea. I looked at this previously and was confused how to detect user inactivity in a reliable way. Any input is appreciated.

**Comment by sumitbhowmick** [comment]
I assume turning keyboard on/off would be easy for LLT, as it will be similar to moving between preset & off.
So I focus on detecting user activity or lack thereof.
We can consider several approaches:
1. Some means to obtain last user input time from windows user32.dll
https://stackoverflow.com/questions/1037595/c-sharp-detect-time-of-last-user-interaction-with-the-os
https://stackoverflow.com/questions/19185/is-there-a-way-to-check-to-see-if-the-user-is-currently-idle?rq=1
https://weblogs.asp.net/jdanforth/454219
https://stackoverflow.com/questions/20611382/how-to-check-mouse-is-not-moved-from-last-5-seconds

Apparently all of them point to this method from MSDN-
https://learn.microsoft.com/en-us/windows/win32/inputdev/keyboard-input
Windows can sense if there is any input or not, before proceeding to sleep/screen off, so there should be a reliable way to fetch that.

2. There is Hotkey feature in LLT & Vantage. How those are captured?
If we can listen for specific Key inputs, can we use it more generic way - any input or not?

3. Microsoft PowerToys include modules like KeyboardManager and KeepAwake. These play around user input detection.
They use different set of libraries, probably more modern approach and finer control of user experience. Maybe worth taking a look. 
https://github.com/microsoft/PowerToys

4. Project https://github.com/ligius-/lenovo-backlight-control rely on AutoHotkey to detect user idle time.
User Idle Time in AutoHotKey can be fetched: https://www.autohotkey.com/docs/v1/Variables.htm#TimeIdle

We can consider using library of another tool like AutoHotKey, as they seem to have a rich community.
They expose some DLLs which can be included to leverage their feature.
https://github.com/ahkscript/awesome-AutoHotkey#libraries-system

5. LLT can expose a function/API which can be called from AHK to trigger keyboard backlight on/off or preset change.

**Comment by sumitbhowmick** [comment]
I assume turning keyboard on/off would be easy for LLT, as it will be similar to moving between preset & off.
So I focus on detecting user activity or lack thereof.
We can consider several approaches:
1. Some means to obtain last user input time from windows user32.dll
https://stackoverflow.com/questions/1037595/c-sharp-detect-time-of-last-user-interaction-with-the-os
https://stackoverflow.com/questions/19185/is-there-a-way-to-check-to-see-if-the-user-is-currently-idle?rq=1
https://weblogs.asp.net/jdanforth/454219
https://stackoverflow.com/questions/20611382/how-to-check-mouse-is-not-moved-from-last-5-seconds

Apparently all of them point to this method from MSDN-
https://learn.microsoft.com/en-us/windows/win32/inputdev/keyboard-input
Windows can sense if there is any input or not, before proceeding to sleep/screen off, so there should be a reliable way to fetch that.

2. There is Hotkey feature in LLT & Vantage. How those are captured?
If we can listen for specific Key inputs, can we use it more generic way - any input or not?

3. Microsoft PowerToys include modules like KeyboardManager and KeepAwake. These play around user input detection.
They use different set of libraries, probably more modern approach and finer control of user experience. Maybe worth taking a look. 
https://github.com/microsoft/PowerToys

4. Project https://github.com/ligius-/lenovo-backlight-control rely on AutoHotkey to detect user idle time.
User Idle Time in AutoHotKey can be fetched: https://www.autohotkey.com/docs/v1/Variables.htm#TimeIdle

We can consider using library of another tool like AutoHotKey, as they seem to have a rich community.
They expose some DLLs which can be included to leverage their feature.
https://github.com/ahkscript/awesome-AutoHotkey#libraries-system

5. LLT can expose a function/API which can be called from AHK to trigger keyboard backlight on/off or preset change.

**Comment by BartoszCichecki** [comment]
Good research, thanks. I have a lot going on now, but will look into this whenever I have time!

**Comment by sumitbhowmick** [comment]
Appreciate you taking time to look at it. Will eagerly look forward to it!

**Comment by Ekscentricitet** [comment]
Hello @BartoszCichecki and @sumitbhowmick,

I looked into the issue and tested a [solution](https://stackoverflow.com/a/11901730) I found on Stack Overflow with a C# console application. It seems to be working and detects if I am using external keyboard or mouse. It also works with the touchpad. I will try to integrate it into the codebase to see if it will work in a tray application.

Since this would be my first contribution, I would greatly appreciate some guidance on which files or modules I should focus on to gain a better understanding of the project's architecture and relevant components. Any specific entry points or key functions that relate to the area I'll be working on would also be super helpful.

**Comment by BartoszCichecki** [comment]
Hi @Ekscentricitet,

It seems like an ok solution. I can see we can query the time since last input using this. We could have a timer checking this in lets say 5 second increments (to avoid doing too much in the background), so that transition from active to idle should be pretty easy using this method.

What about transitioning from idle to active? Sounds like we might need a keyboard/mouse hook to make the transition instantanous?

**Comment by Ekscentricitet** [comment]
I was thinking about it today. We can let the user choose inactivity time in seconds (let's denote it by S). When the option is turned on (or the program starts with the option turned on), start the timer for S seconds. When the S seconds pass, check for how long the user was inactive (let's denote it by I). If the value is less than S (I < S), start a new timer for the duration N, where N = S - I (the inactivity time set by the user minus the actual inactivity time since the last check). In this way we should minimize the number of times we call system functions to check for the user's activity, while at the same time we are as precise as possible with the user-defined inactivity time setting. I am not sure how will this work when the laptop goes to sleep. We might need a different event to reset the timer when it wakes up.

When the inactivity time _I_ becomes bigger than the threshold (I > S), stop the timer and attach to a global system hook, such as [WH_MOUSE_LL](https://learn.microsoft.com/en-us/windows/win32/winmsg/about-hooks#wh_mouse) and [WH_KEYBOARD_LL](https://learn.microsoft.com/en-us/windows/win32/winmsg/about-hooks#wh_keyboard) to immediately know when the user is active, as you proposed. When the user becomes active, simply restart the timer as if the function has just been turned on. I haven't worked with hooks before and if we decide to go this way I will read more about them. For example, I am not sure if the application won't need additional permissions.

We could also go a step further and turn this into a new Listener, such that the user can perform other useful Actions. For example, turning off HDR or lowering the refresh rate also seem useful to do to save energy. However, I am not sure if in the current architecture we could easily integrate setting the timer length by the user with this approach. We could add it as a separate setting, but then the user would have to change two things in two different places.

**Comment by sumitbhowmick** [comment]
Program can ship with a default settings (timeout & on/off). Then program should retain the user choice.
Deactivation & activation logic sounds good, subject to actual PoC outcome.

I was thinking about making this feature as a switch/option/preset (God mode preset?) in Keyboard page, where this option can be utilised in all/selected presets and all power conditions (AC/battery). I doubt anyone running Wave RGB will choose to suddenly stop the RGB when idle (maybe watching game video), but doesn't hurt to provide the option where feasible.

Turning this into an Action step will definitely add value, if user wants to have on-demand backlight on battery, but wants to keep it on all the time on AC power. I guess that would still require the first feature/capability to work smoothly. Also, if someone doesn't want to play around with Actions, they can still go to Keyboard tab and indicate their preference.

If configuration for an action is feasible, that will be a value add where users can perform various things on the idle event/active detection. But I believe there would be different use cases, and it won't hurt to have the options in more than one places.

**Comment by sumitbhowmick** [comment]
@BartoszCichecki @Ekscentricitet I was exploring Legion RGB Control project https://github.com/4JX/L5P-Keyboard-RGB fade effect.
It works the way I was looking for. The backlight slowly (awesome) goes off on keyboard inactivity, and comes back immediately when a key is pressed. It doesn't have any link to touchpad usage, which kinda makes sense. I think we can give user choice between selecting only keyboard inactivity or both keyboard+touchpad inactivity/activity.
Of course, it doesn't have the finesse of LLT like nice UI, autostart and everything LLT is worth for.
I think we can look at their implementation and enrich LLT with its vast options of backlight control.

**Comment by BartoszCichecki** [comment]
> The backlight slowly (awesome) goes off on keyboard inactivity

That might be one of the reasons why CPU usage is high. They are emulating some features that are not supported natively by the rgb controller.

> I think we can give user choice between selecting only keyboard inactivity or both keyboard+touchpad inactivity/activity

I think we should just listen to both kb and mouse.

> It takes up about 2-4% CPU all the time (highest 6%)

That is way to high. A feature like this one should have no visible impact, so we need to keep it in mind.

**Comment by Ekscentricitet** [comment]
How do we proceed? What changes have to be made?

**Comment by BartoszCichecki** [comment]
> How do we proceed? What changes have to be made?

I did a small spike (see linked PR) and managed to get this working with Spectrum controller. It's a little bit more complex than I thought, but the progress so far seems good.

Will keep you posted.

**Comment by BartoszCichecki** [comment]
OK I moved it to Actions in the end, it's more flexible. Here is a sample from an early build:

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/7916915/ab611d73-15a7-472b-8e2b-c512bcd44af6)

**Comment by sumitbhowmick** [comment]
Thanks @BartoszCichecki & @Ekscentricitet for the awesome work!
Is there a test build available with this feature? I'm happy to have a first look.

Is there any option to configure the duration of inactivity to trigger user inactive state?
Any option to define inactivity/activity based on keyboard AND/OR touchpad?

**Comment by BartoszCichecki** [comment]
In the Readme there is discord server linked. LLT has a dedicated channel there where beta versions are posted. You can check the beta build there 😉

Inactivity timeout is configurable between 10s and 30m and it responds to both kb and mouse (touchpad is de facto mouse from Windows' point of view).
