### ISSUE TITLE
[BUG]: BSOD when opening 2.14 on 16ACHg6 (82N6)

### ISSUE THREAD

**Issue by uOoOnu** [BartoszCichecki/LenovoLegionToolkit#809]
### Version

2.14.0/2.14.1

### OS

Windows 11 22H2 Build 22621

### Device

Legion 7 16ACHg6 82N6

### BIOS version

GKCN44WW

### What's wrong?

In versions 2.14.0 and 2.14.1 when starting the app the window will open and the loading symbol will appear:
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/137457202/abc275c2-dcaf-453c-a803-9738f2a20f0d)
but will BSOD before the menu can appear. (BSOD details below)
Does not occur in 2.13.2. 

Unsure if related: 2.14.0 / 2.14.1 don't appear in "installed apps" to uninstall them while 2.13.2 does

### How to reproduce the bug?

1. Open LLT on 2.14.0 or 2.14.1
2. Wait for UI to show up and loading icon to turn for a bit
3. BSOD

### What is the behavior that you expected?

N/A

### Logs

[log_2023_06_22_23_34_02.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11841257/log_2023_06_22_23_34_02.txt)

BSOD Minidump info:
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/137457202/5708a227-5617-4095-ac75-2a82d0367763)

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

Funny BSOD
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/137457202/d0407538-e4d8-4af9-b5e2-9cad06e979dd)

**Comment by BartoszCichecki** [comment]
It looks like what BSODs your system is the WMI provider that interfaces with ACPI (basically the EC), it is difficult to say why, but we can try to troubleshoot.

2.14 added couple new calls: check for GPU OC support and lighting methods (for panel and rear ports lights). That said, neither of these calls should cause BSODs, because they are standard methods used by Vantage and LegionZone.

I prepared 4 builds that turn, each disables one of the new things added in 2.14 that is related to your issue. You can try to see if you notice any differences:
[LenovoLegionToolkitSetup_1.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11849060/LenovoLegionToolkitSetup_1.zip)
[LenovoLegionToolkitSetup_2.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11849061/LenovoLegionToolkitSetup_2.zip)
[LenovoLegionToolkitSetup_3.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11849058/LenovoLegionToolkitSetup_3.zip)
[LenovoLegionToolkitSetup_4.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11849086/LenovoLegionToolkitSetup_4.zip)

Let me know what are the results.

**Comment by uOoOnu** [comment]
[LenovoLegionToolkitSetup_1.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11849060/LenovoLegionToolkitSetup_1.zip) 
works without BSOD, all the others BSOD (as expected)

**Comment by uOoOnu** [comment]
All of them cause the BSOD, though the first one causes a weirder looking one

**Comment by BartoszCichecki** [comment]
Here is a build that will not call any of these methods on this Legion model. The reason of BSODs is most likely a broken implementation of one of the ACPI calls, so some features like panel, ports and white keyboard backlight will not be available.

Can you try and see if it works properly?

[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11857160/LenovoLegionToolkitSetup.zip)

**Comment by BartoszCichecki** [comment]
After talking to couple of other people BIOS version GKCN44WW was identified to be the culprit. Minimum version for panel logo, rear ports lighting and white keyboard backlight was raised to GKCN54WW.
