### ISSUE TITLE
Hope to support infinitely adjustable fan speed

### ISSUE THREAD

**Issue by Danyhug** [BartoszCichecki/LenovoLegionToolkit#982]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

all

### OS

windows11

### Device

R9000P 2023 7745+4060

### Is your feature request related to a problem?

Hope to support infinitely adjustable fan speed

### How would you like the problem to be solved?

Hope to support infinitely adjustable fan speed

### What alternatives have you considered?

Legionfancontrol can be adjusted for older versions of Lenovo computers

**Comment by BartoszCichecki** [comment]
Current implementation has everything that is possible, more customization isn't possible.

**Comment by Wolvverine** [comment]
@BartoszCichecki look here:

https://github.com/johnfanv2/LenovoLegionLinux

**Comment by BartoszCichecki** [comment]
This method involves writing directly to EC memory which is neither safe and requires different implementation for each gen.

**Comment by spfmoby** [comment]
isn't it possible to tweak to things:
- for a specific fan step set the rpm (or voltage) of this step. For example on my new Legion 7i (gen 9) the first step is 1700 rpm which is way too loud and makes the on/off switch of the fan very noticable.
- change the initial speed of the fan when it starts up, because when it goes from off to on it begins by ramping very high (probably around 400rpm) for a second or two then decreases to 1700 rpm. This behaviour is really annoying.
